theme: minima
title: FJZ Bioinfo Notes
description: Bioinformatics notes, tutorials, and insights by FJZ
author: Dr. rer. nat. Fengjun Zhang
url: https://fzhang12.github.io

# Plugins
plugins:
  - jekyll-feed

# Minima options
show_excerpts: true

# Navigation (top right corner)
header_pages:
  - about.md
  - tags/index.md

# Optional social links (uncomment and fill later)
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/fzhang12" }